"""
THE STOCK LOGIC — Zerodha Instrument Token Map Builder
=======================================================
Downloads Zerodha's public instruments CSV and generates
ZERODHA_TOKEN_MAP for all 500 universe stocks.

Output: engine/zerodha_tokens.py (auto-generated)

Run: python3 engine/build_zerodha_tokens.py
"""
import sys, csv, io
from pathlib import Path
import requests

sys.path.insert(0, str(Path(__file__).parent))
from universe import SYMBOL_SECTOR_MAP

def main():
    print("Downloading Zerodha instruments dump...")
    r = requests.get("https://api.kite.trade/instruments", timeout=60)
    r.raise_for_status()

    reader = csv.DictReader(io.StringIO(r.text))
    # Build NSE equity map: symbol -> instrument_token
    nse_eq = {}
    for row in reader:
        if row["exchange"] == "NSE" and row["instrument_type"] == "EQ":
            nse_eq[row["tradingsymbol"]] = int(row["instrument_token"])

    print(f"Zerodha NSE EQ instruments: {len(nse_eq)}")

    found, missing = {}, []
    for sym in SYMBOL_SECTOR_MAP:
        if sym in nse_eq:
            found[sym] = nse_eq[sym]
        else:
            missing.append(sym)

    print(f"Mapped: {len(found)} | Missing: {len(missing)}")
    if missing:
        print(f"Missing symbols: {missing[:20]}")

    # Write the token map
    out = Path(__file__).parent / "zerodha_tokens.py"
    with open(out, "w") as f:
        f.write('"""\n')
        f.write("THE STOCK LOGIC — Zerodha Instrument Tokens\n")
        f.write("=============================================\n")
        f.write("Auto-generated by build_zerodha_tokens.py. Do not edit.\n")
        f.write(f"Mapped: {len(found)} stocks\n")
        f.write('"""\n\n')
        f.write("ZERODHA_TOKEN_MAP = {\n")
        for sym, tok in sorted(found.items()):
            f.write(f'    "{sym}": {tok},\n')
        f.write("}\n\n")
        f.write("TOKEN_SYMBOL_MAP = {v: k for k, v in ZERODHA_TOKEN_MAP.items()}\n")

    print(f"Written: {out}")

if __name__ == "__main__":
    main()
