-- Audit actions 1, 3 and 5: the sector bug, the publication_kind label leak,
-- and the derived fields marked as derived.
--
-- Three unrelated fixes in one file because each is two statements and they touch
-- one table. Apply ONE STATEMENT AT A TIME -- three of the last six migrations
-- here applied only a prefix and reported success. See migrations/README.md.

-- ─────────────────────────────────────────────────────────────────────
-- 1. SECTOR. 03b has always computed it from universe.SYMBOL_SECTOR_MAP;
--    06_push's 36-key literal dropped it; update_outcomes and trade_review
--    then read it off the signals row with `.get("sector", "OTHER")`. The
--    column did not exist, so the default fired on EVERY row, and all 831
--    outcome rows written since 2025-05-12 say OTHER.
--
--    The default is why it was silent for seventeen months. Seven earlier
--    field-name mismatches in this repo each surfaced as a PostgREST 400,
--    because selecting an absent column errors. A .get() with a fallback is
--    the one access pattern that cannot.
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.signals ADD COLUMN IF NOT EXISTS sector       text;
ALTER TABLE public.signals ADD COLUMN IF NOT EXISTS sector_bias  text;
ALTER TABLE public.signals ADD COLUMN IF NOT EXISTS sector_as_of text;

-- The backfill, and WHY IT IS FLAGGED. This writes today's sector map onto rows
-- published as far back as May 2025. A symbol reclassified since then gets its
-- CURRENT sector, not the one in force when the signal was published -- so this
-- replaces a known-wrong constant with a possibly-wrong value, which would be
-- the worse trade if nothing recorded the difference.
--
-- sector_as_of = 'backfill-2026-10-02' marks every imputed row. 06_push writes
-- 'recorded' on rows it publishes from now on. Any analysis can then filter to
-- sectors that were actually observed, and a sector-conditioned finding built on
-- imputed rows cannot be mistaken for one built on recorded ones.
WITH m(symbol, sector) AS (VALUES
  ('360ONE','FINANCE'),
  ('3MINDIA','INFRA'),
  ('AADHARHFC','FINANCE'),
  ('AARTIDRUGS','PHARMA'),
  ('AARTIIND','METAL'),
  ('AARTIPHARM','PHARMA'),
  ('AAVAS','FINANCE'),
  ('ABB','INFRA'),
  ('ABBOTINDIA','PHARMA'),
  ('ABCAPITAL','FINANCE'),
  ('ABDL','FMCG'),
  ('ABFRL','FMCG'),
  ('ABLBL','FMCG'),
  ('ABREL','REALTY'),
  ('ABSLAMC','FINANCE'),
  ('ACC','INFRA'),
  ('ACE','INFRA'),
  ('ACI','METAL'),
  ('ACMESOLAR','ENERGY'),
  ('ACUTAAS','PHARMA'),
  ('ADANIENSOL','ENERGY'),
  ('ADANIENT','METAL'),
  ('ADANIGREEN','ENERGY'),
  ('ADANIPORTS','INFRA'),
  ('ADANIPOWER','ENERGY'),
  ('ADVENZYMES','PHARMA'),
  ('AEGISLOG','ENERGY'),
  ('AEGISVOPAK','ENERGY'),
  ('AETHER','METAL'),
  ('AFCONS','INFRA'),
  ('AFFLE','IT'),
  ('AGARWALEYE','PHARMA'),
  ('AIAENG','INFRA'),
  ('AIIL','FINANCE'),
  ('AJANTPHARM','PHARMA'),
  ('AKUMS','PHARMA'),
  ('ALIVUS','PHARMA'),
  ('ALKEM','PHARMA'),
  ('ALKYLAMINE','METAL'),
  ('AMBER','FMCG'),
  ('AMBUJACEM','INFRA'),
  ('ANANDRATHI','FINANCE'),
  ('ANANTRAJ','REALTY'),
  ('ANGELONE','FINANCE'),
  ('ANTHEM','PHARMA'),
  ('ANUP','INFRA'),
  ('ANURAS','METAL'),
  ('APARINDS','INFRA'),
  ('APLAPOLLO','INFRA'),
  ('APLLTD','PHARMA'),
  ('APOLLO','INFRA'),
  ('APOLLOHOSP','PHARMA'),
  ('APOLLOTYRE','AUTO'),
  ('APTUS','FINANCE'),
  ('ARE&M','AUTO'),
  ('ARVIND','FMCG'),
  ('ARVINDFASN','FMCG'),
  ('ASAHIINDIA','AUTO'),
  ('ASHAPURMIN','METAL'),
  ('ASHOKA','INFRA'),
  ('ASHOKLEY','INFRA'),
  ('ASIANPAINT','FMCG'),
  ('ASIANTILES','FMCG'),
  ('ASKAUTOLTD','AUTO'),
  ('ASTERDM','PHARMA'),
  ('ASTRAL','INFRA'),
  ('ASTRAMICRO','INFRA'),
  ('ASTRAZEN','PHARMA'),
  ('ATGL','ENERGY'),
  ('ATHERENERG','AUTO'),
  ('ATUL','METAL'),
  ('AUBANK','BANKING'),
  ('AURIONPRO','IT'),
  ('AUROPHARMA','PHARMA'),
  ('AVALON','INFRA'),
  ('AVANTIFEED','FMCG'),
  ('AVL','FMCG'),
  ('AWL','FMCG'),
  ('AXISBANK','BANKING'),
  ('AZAD','INFRA'),
  ('BAJAJ-AUTO','AUTO'),
  ('BAJAJFINSV','FINANCE'),
  ('BAJAJHFL','FINANCE'),
  ('BAJAJHLDNG','FINANCE'),
  ('BAJFINANCE','FINANCE'),
  ('BALAMINES','METAL'),
  ('BALKRISIND','AUTO'),
  ('BALRAMCHIN','FMCG'),
  ('BALUFORGE','INFRA'),
  ('BANCOINDIA','AUTO'),
  ('BANDHANBNK','BANKING'),
  ('BANKBARODA','BANKING'),
  ('BANKINDIA','FINANCE'),
  ('BASF','METAL'),
  ('BATAINDIA','FMCG'),
  ('BAYERCROP','METAL'),
  ('BBL','INFRA'),
  ('BBOX','IT'),
  ('BBTC','FMCG'),
  ('BDL','DEFENCE'),
  ('BECTORFOOD','FMCG'),
  ('BEL','DEFENCE'),
  ('BELRISE','AUTO'),
  ('BEML','DEFENCE'),
  ('BERGEPAINT','FMCG'),
  ('BHARATFORG','AUTO'),
  ('BHARTIARTL','TELECOM'),
  ('BHARTIHEXA','TELECOM'),
  ('BHEL','INFRA'),
  ('BIKAJI','FMCG'),
  ('BIOCON','PHARMA'),
  ('BIRLACORPN','INFRA'),
  ('BLS','FMCG'),
  ('BLUEDART','INFRA'),
  ('BLUEJET','PHARMA'),
  ('BLUESTARCO','FMCG'),
  ('BLUESTONE','FMCG'),
  ('BOMDYEING','FMCG'),
  ('BORORENEW','INFRA'),
  ('BOSCHLTD','AUTO'),
  ('BPCL','ENERGY'),
  ('BRIGADE','REALTY'),
  ('BRITANNIA','FMCG'),
  ('BSE','FINANCE'),
  ('BSOFT','IT'),
  ('CAMPUS','FMCG'),
  ('CAMS','FINANCE'),
  ('CANBK','BANKING'),
  ('CANFINHOME','FINANCE'),
  ('CANHLIFE','FINANCE'),
  ('CAPLIPOINT','PHARMA'),
  ('CARBORUNIV','INFRA'),
  ('CARERATING','FINANCE'),
  ('CARTRADE','FMCG'),
  ('CASTROLIND','ENERGY'),
  ('CCL','FMCG'),
  ('CDSL','FINANCE'),
  ('CEATLTD','AUTO'),
  ('CELLO','FMCG'),
  ('CEMPRO','INFRA'),
  ('CENTRALBK','FINANCE'),
  ('CENTUM','INFRA'),
  ('CERA','FMCG'),
  ('CESC','ENERGY'),
  ('CGCL','FINANCE'),
  ('CGPOWER','INFRA'),
  ('CHALET','FMCG'),
  ('CHAMBLFERT','METAL'),
  ('CHENNPETRO','ENERGY'),
  ('CHOICEIN','FINANCE'),
  ('CHOLAFIN','FINANCE'),
  ('CHOLAHLDNG','FINANCE'),
  ('CIEINDIA','AUTO'),
  ('CIPLA','PHARMA'),
  ('CLEAN','METAL'),
  ('COALINDIA','METAL'),
  ('COCHINSHIP','DEFENCE'),
  ('COFORGE','IT'),
  ('COHANCE','PHARMA'),
  ('COLPAL','FMCG'),
  ('CONCOR','INFRA'),
  ('CONCORDBIO','PHARMA'),
  ('COROMANDEL','METAL'),
  ('CPPLUS','INFRA'),
  ('CRAFTSMAN','AUTO'),
  ('CREDITACC','FINANCE'),
  ('CRISIL','FINANCE'),
  ('CRIZAC','FMCG'),
  ('CROMPTON','FMCG'),
  ('CSBBANK','FINANCE'),
  ('CUB','FINANCE'),
  ('CUMMINSIND','INFRA'),
  ('CUPID','FMCG'),
  ('CYIENT','IT'),
  ('DABUR','FMCG'),
  ('DALBHARAT','INFRA'),
  ('DATAMATICS','IT'),
  ('DATAPATTNS','INFRA'),
  ('DBL','INFRA'),
  ('DCBBANK','FINANCE'),
  ('DCMSHRIRAM','METAL'),
  ('DEEPAKFERT','METAL'),
  ('DEEPAKNTR','METAL'),
  ('DELHIVERY','INFRA'),
  ('DELTACORP','INFRA'),
  ('DEVYANI','FMCG'),
  ('DIVISLAB','PHARMA'),
  ('DIXON','FMCG'),
  ('DLF','REALTY'),
  ('DMART','FMCG'),
  ('DOMS','FMCG'),
  ('DREDGECORP','INFRA'),
  ('DRREDDY','PHARMA'),
  ('DYNAMATECH','INFRA'),
  ('ECLERX','IT'),
  ('EDELWEISS','FINANCE'),
  ('EICHERMOT','AUTO'),
  ('EIDPARRY','FMCG'),
  ('EIEL','ENERGY'),
  ('EIHOTEL','FMCG'),
  ('ELECON','INFRA'),
  ('ELECTCAST','INFRA'),
  ('ELGIEQUIP','INFRA'),
  ('ELLEN','METAL'),
  ('EMAMILTD','FMCG'),
  ('EMCURE','PHARMA'),
  ('EMIL','FMCG'),
  ('EMMVEE','INFRA'),
  ('ENDURANCE','AUTO'),
  ('ENGINERSIN','INFRA'),
  ('ENRIN','INFRA'),
  ('ENTERO','FMCG'),
  ('EPL','INFRA'),
  ('EQUITASBNK','FINANCE'),
  ('ERIS','PHARMA'),
  ('ESCORTS','INFRA'),
  ('ETERNAL','FMCG'),
  ('ETHOSLTD','FMCG'),
  ('EUREKAFORB','FMCG'),
  ('EXIDEIND','AUTO'),
  ('FACT','METAL'),
  ('FEDERALBNK','BANKING'),
  ('FEDFINA','FINANCE'),
  ('FIEMIND','AUTO'),
  ('FINCABLES','INFRA'),
  ('FINPIPE','INFRA'),
  ('FIRSTCRY','FMCG'),
  ('FIVESTAR','FINANCE'),
  ('FLUOROCHEM','METAL'),
  ('FORCEMOT','AUTO'),
  ('FORTIS','PHARMA'),
  ('FSL','IT'),
  ('GABRIEL','AUTO'),
  ('GAEL','FMCG'),
  ('GAIL','ENERGY'),
  ('GALLANTT','INFRA'),
  ('GENESYS','IT'),
  ('GENUSPOWER','INFRA'),
  ('GESHIP','INFRA'),
  ('GHCL','METAL'),
  ('GICRE','FINANCE'),
  ('GILLETTE','FMCG'),
  ('GLAND','PHARMA'),
  ('GLAXO','PHARMA'),
  ('GLENMARK','PHARMA'),
  ('GLOBUSSPR','FMCG'),
  ('GMBREW','FMCG'),
  ('GMDCLTD','METAL'),
  ('GMMPFAUDLR','INFRA'),
  ('GMRAIRPORT','FINANCE'),
  ('GMRP&UI','ENERGY'),
  ('GNFC','METAL'),
  ('GODFRYPHLP','FMCG'),
  ('GODIGIT','FINANCE'),
  ('GODREJAGRO','FMCG'),
  ('GODREJCP','FMCG'),
  ('GODREJIND','METAL'),
  ('GODREJPROP','REALTY'),
  ('GOKEX','FMCG'),
  ('GOKULAGRO','FMCG'),
  ('GOLDIAM','FMCG'),
  ('GPIL','INFRA'),
  ('GPPL','INFRA'),
  ('GRANULES','PHARMA'),
  ('GRAPHITE','INFRA'),
  ('GRASIM','INFRA'),
  ('GRAVITA','METAL'),
  ('GREAVESCOT','INFRA'),
  ('GRINDWELL','INFRA'),
  ('GROWW','FINANCE'),
  ('GRSE','DEFENCE'),
  ('GRWRHITECH','INFRA'),
  ('GSFC','METAL'),
  ('GVT&D','INFRA'),
  ('HAL','DEFENCE'),
  ('HAPPSTMNDS','IT'),
  ('HAVELLS','FMCG'),
  ('HBLENGINE','INFRA'),
  ('HCG','PHARMA'),
  ('HCLTECH','IT'),
  ('HDBFS','FINANCE'),
  ('HDFCAMC','FINANCE'),
  ('HDFCBANK','BANKING'),
  ('HDFCLIFE','FINANCE'),
  ('HEG','INFRA'),
  ('HERITGFOOD','FMCG'),
  ('HEROMOTOCO','AUTO'),
  ('HEXT','IT'),
  ('HFCL','IT'),
  ('HGINFRA','INFRA'),
  ('HIKAL','PHARMA'),
  ('HINDALCO','METAL'),
  ('HINDCOPPER','METAL'),
  ('HINDOILEXP','ENERGY'),
  ('HINDPETRO','ENERGY'),
  ('HINDUNILVR','FMCG'),
  ('HINDZINC','METAL'),
  ('HIRECT','INFRA'),
  ('HOMEFIRST','FINANCE'),
  ('HONASA','FMCG'),
  ('HONAUT','INFRA'),
  ('HSCL','METAL'),
  ('HUBTOWN','INFRA'),
  ('HUDCO','FINANCE'),
  ('HYUNDAI','AUTO'),
  ('ICICIAMC','FINANCE'),
  ('ICICIBANK','BANKING'),
  ('ICICIGI','FINANCE'),
  ('ICICIPRULI','FINANCE'),
  ('ICIL','FMCG'),
  ('IDBI','FINANCE'),
  ('IDEA','IT'),
  ('IDFCFIRSTB','BANKING'),
  ('IEX','FINANCE'),
  ('IFBIND','FMCG'),
  ('IFCI','FINANCE'),
  ('IGIL','FINANCE'),
  ('IGL','ENERGY'),
  ('IIFL','FINANCE'),
  ('IIFLCAPS','FINANCE'),
  ('IKS','IT'),
  ('IMFA','METAL'),
  ('INDGN','PHARMA'),
  ('INDHOTEL','FMCG'),
  ('INDIACEM','INFRA'),
  ('INDIAGLYCO','FMCG'),
  ('INDIAMART','IT'),
  ('INDIANB','FINANCE'),
  ('INDIASHLTR','FINANCE'),
  ('INDIGO','INFRA'),
  ('INDIGOPNTS','FMCG'),
  ('INDUSINDBK','BANKING'),
  ('INDUSTOWER','TELECOM'),
  ('INFY','IT'),
  ('INOXINDIA','INFRA'),
  ('INOXWIND','INFRA'),
  ('INTELLECT','IT'),
  ('IOB','FINANCE'),
  ('IOC','ENERGY'),
  ('IOLCP','PHARMA'),
  ('IONEXCHANG','ENERGY'),
  ('IPCALAB','PHARMA'),
  ('IRB','INFRA'),
  ('IRCON','INFRA'),
  ('IRCTC','FMCG'),
  ('IREDA','FINANCE'),
  ('IRFC','FINANCE'),
  ('ITC','FMCG'),
  ('ITCHOTELS','FMCG'),
  ('ITI','TELECOM'),
  ('IXIGO','FMCG'),
  ('J&KBANK','FINANCE'),
  ('JAICORPLTD','METAL'),
  ('JAINREC','METAL'),
  ('JAMNAAUTO','AUTO'),
  ('JAYNECOIND','INFRA'),
  ('JBCHEPHARM','PHARMA'),
  ('JBMA','AUTO'),
  ('JINDALSAW','INFRA'),
  ('JINDALSTEL','METAL'),
  ('JINDRILL','ENERGY'),
  ('JIOFIN','FINANCE'),
  ('JKCEMENT','INFRA'),
  ('JKIL','INFRA'),
  ('JKLAKSHMI','INFRA'),
  ('JKPAPER','METAL'),
  ('JKTYRE','AUTO'),
  ('JMFINANCIL','FINANCE'),
  ('JPPOWER','ENERGY'),
  ('JSFB','FINANCE'),
  ('JSL','METAL'),
  ('JSLL','FMCG'),
  ('JSWCEMENT','INFRA'),
  ('JSWDULUX','FMCG'),
  ('JSWENERGY','ENERGY'),
  ('JSWINFRA','INFRA'),
  ('JSWSTEEL','METAL'),
  ('JUBLFOOD','FMCG'),
  ('JUBLINGREA','METAL'),
  ('JUBLPHARMA','PHARMA'),
  ('JUSTDIAL','FMCG'),
  ('JWL','INFRA'),
  ('JYOTHYLAB','FMCG'),
  ('JYOTICNC','INFRA'),
  ('KAJARIACER','FMCG'),
  ('KALYANKJIL','FMCG'),
  ('KANSAINER','FMCG'),
  ('KARURVYSYA','BANKING'),
  ('KAYNES','INFRA'),
  ('KEC','INFRA'),
  ('KEI','INFRA'),
  ('KERNEX','IT'),
  ('KFINTECH','FINANCE'),
  ('KIMS','PHARMA'),
  ('KIRIINDUS','METAL'),
  ('KIRLOSBROS','INFRA'),
  ('KIRLOSENG','INFRA'),
  ('KIRLPNU','INFRA'),
  ('KITEX','FMCG'),
  ('KNRCON','INFRA'),
  ('KOTAKBANK','BANKING'),
  ('KPIGREEN','ENERGY'),
  ('KPIL','INFRA'),
  ('KPITTECH','IT'),
  ('KPRMILL','FMCG'),
  ('KRBL','FMCG'),
  ('KSB','INFRA'),
  ('KSCL','FMCG'),
  ('KTKBANK','FINANCE'),
  ('LALPATHLAB','PHARMA'),
  ('LATENTVIEW','IT'),
  ('LAURUSLABS','PHARMA'),
  ('LEMONTREE','FMCG'),
  ('LENSKART','FMCG'),
  ('LGEINDIA','FMCG'),
  ('LICHSGFIN','FINANCE'),
  ('LICI','FINANCE'),
  ('LINDEINDIA','METAL'),
  ('LLOYDSENGG','INFRA'),
  ('LLOYDSENT','METAL'),
  ('LLOYDSME','METAL'),
  ('LODHA','REALTY'),
  ('LT','INFRA'),
  ('LTF','FINANCE'),
  ('LTFOODS','FMCG'),
  ('LTM','IT'),
  ('LTTS','IT'),
  ('LUMAXIND','AUTO'),
  ('LUMAXTECH','AUTO'),
  ('LUPIN','PHARMA'),
  ('LXCHEM','METAL'),
  ('M&M','AUTO'),
  ('M&MFIN','FINANCE'),
  ('MAHABANK','FINANCE'),
  ('MAHSCOOTER','FINANCE'),
  ('MAHSEAMLES','INFRA'),
  ('MANAPPURAM','FINANCE'),
  ('MANINDS','METAL'),
  ('MANINFRA','INFRA'),
  ('MANKIND','PHARMA'),
  ('MANORAMA','FMCG'),
  ('MANYAVAR','FMCG'),
  ('MAPMYINDIA','IT'),
  ('MARICO','FMCG'),
  ('MARKSANS','PHARMA'),
  ('MARUTI','AUTO'),
  ('MASTEK','IT'),
  ('MAXHEALTH','PHARMA'),
  ('MAZDOCK','DEFENCE'),
  ('MCX','FINANCE'),
  ('MEDANTA','PHARMA'),
  ('MEDPLUS','FMCG'),
  ('MEESHO','FMCG'),
  ('METROPOLIS','PHARMA'),
  ('MFSL','FINANCE'),
  ('MGL','ENERGY'),
  ('MIDHANI','INFRA'),
  ('MINDACORP','AUTO'),
  ('MMTC','METAL'),
  ('MOIL','METAL'),
  ('MOREPENLAB','PHARMA'),
  ('MOTHERSON','AUTO'),
  ('MOTILALOFS','FINANCE'),
  ('MPHASIS','IT'),
  ('MRF','AUTO'),
  ('MRPL','ENERGY'),
  ('MSUMI','AUTO'),
  ('MUTHOOTFIN','FINANCE'),
  ('NAM-INDIA','FINANCE'),
  ('NATCOPHARM','PHARMA'),
  ('NATIONALUM','METAL'),
  ('NAUKRI','IT'),
  ('NAVA','ENERGY'),
  ('NAVINFLUOR','METAL'),
  ('NAZARA','FMCG'),
  ('NBCC','INFRA'),
  ('NCC','INFRA'),
  ('NELCO','IT'),
  ('NEOGEN','METAL'),
  ('NESTLEIND','FMCG'),
  ('NETWEB','IT'),
  ('NEULANDLAB','PHARMA'),
  ('NEWGEN','IT'),
  ('NFL','METAL'),
  ('NH','PHARMA'),
  ('NHPC','ENERGY'),
  ('NIACL','FINANCE'),
  ('NIVABUPA','FINANCE'),
  ('NLCINDIA','ENERGY'),
  ('NMDC','METAL'),
  ('NOCIL','METAL'),
  ('NSLNISP','METAL'),
  ('NTPC','ENERGY'),
  ('NTPCGREEN','ENERGY'),
  ('NUVAMA','FINANCE'),
  ('NUVOCO','INFRA'),
  ('NYKAA','FMCG'),
  ('OBEROIRLTY','REALTY'),
  ('OFSS','IT'),
  ('OIL','ENERGY'),
  ('OLAELEC','AUTO'),
  ('OLECTRA','AUTO'),
  ('ONESOURCE','PHARMA'),
  ('ONGC','ENERGY'),
  ('OPTIEMUS','TELECOM'),
  ('ORIENTCEM','INFRA'),
  ('OSWALPUMPS','INFRA'),
  ('PAGEIND','FMCG'),
  ('PANACEABIO','PHARMA'),
  ('PARADEEP','METAL'),
  ('PARAS','INFRA'),
  ('PATANJALI','FMCG'),
  ('PAYTM','FINANCE'),
  ('PCBL','METAL'),
  ('PENIND','METAL'),
  ('PERSISTENT','IT'),
  ('PETRONET','ENERGY'),
  ('PFC','FINANCE'),
  ('PFIZER','PHARMA'),
  ('PFOCUS','FMCG'),
  ('PGEL','FMCG'),
  ('PGHH','FMCG'),
  ('PGIL','FMCG'),
  ('PHOENIXLTD','REALTY'),
  ('PICCADIL','FMCG'),
  ('PIDILITIND','METAL'),
  ('PIIND','METAL'),
  ('PINELABS','FINANCE'),
  ('PIRAMALFIN','FINANCE'),
  ('PNB','BANKING'),
  ('PNBHOUSING','FINANCE'),
  ('PNCINFRA','INFRA'),
  ('PNGJL','FMCG'),
  ('POLICYBZR','FINANCE'),
  ('POLYCAB','INFRA'),
  ('POLYMED','PHARMA'),
  ('POLYPLEX','METAL'),
  ('POONAWALLA','FINANCE'),
  ('POWERGRID','ENERGY'),
  ('POWERINDIA','INFRA'),
  ('POWERMECH','INFRA'),
  ('PPLPHARMA','PHARMA'),
  ('PRAJIND','INFRA'),
  ('PRAKASH','METAL'),
  ('PRECWIRE','METAL'),
  ('PREMIERENE','INFRA'),
  ('PRESTIGE','REALTY'),
  ('PRICOLLTD','AUTO'),
  ('PRIVISCL','METAL'),
  ('PRUDENT','FINANCE'),
  ('PTC','ENERGY'),
  ('PTCIL','INFRA'),
  ('PVRINOX','FMCG'),
  ('PWL','FMCG'),
  ('RADICO','FMCG'),
  ('RAILTEL','IT'),
  ('RAIN','METAL'),
  ('RAINBOW','PHARMA'),
  ('RALLIS','METAL'),
  ('RAMCOCEM','INFRA'),
  ('RATEGAIN','IT'),
  ('RATNAMANI','INFRA'),
  ('RAYMOND','FMCG'),
  ('RAYMONDLSL','FMCG'),
  ('RBA','FMCG'),
  ('RBLBANK','BANKING'),
  ('RCF','METAL'),
  ('RECLTD','FINANCE'),
  ('REDINGTON','IT'),
  ('REFEX','ENERGY'),
  ('RELIANCE','ENERGY'),
  ('RELIGARE','FINANCE'),
  ('RHIM','INFRA'),
  ('RICOAUTO','AUTO'),
  ('RITES','INFRA'),
  ('RKFORGE','AUTO'),
  ('ROUTE','TELECOM'),
  ('RPOWER','ENERGY'),
  ('RRKABEL','INFRA'),
  ('RVNL','INFRA'),
  ('SAFARI','FMCG'),
  ('SAGILITY','IT'),
  ('SAIL','METAL'),
  ('SAILIFE','PHARMA'),
  ('SAMHI','FMCG'),
  ('SAMMAANCAP','FINANCE'),
  ('SANDUMA','METAL'),
  ('SANGHVIMOV','INFRA'),
  ('SANOFI','PHARMA'),
  ('SANSERA','AUTO'),
  ('SAPPHIRE','FMCG'),
  ('SARDAEN','METAL'),
  ('SAREGAMA','FMCG'),
  ('SBFC','FINANCE'),
  ('SBICARD','FINANCE'),
  ('SBILIFE','FINANCE'),
  ('SBIN','BANKING'),
  ('SCHAEFFLER','AUTO'),
  ('SCHNEIDER','INFRA'),
  ('SCI','INFRA'),
  ('SEAMECLTD','INFRA'),
  ('SENCO','FMCG'),
  ('SFL','FMCG'),
  ('SHAILY','FMCG'),
  ('SHAKTIPUMP','INFRA'),
  ('SHARDACROP','METAL'),
  ('SHAREINDIA','FINANCE'),
  ('SHILPAMED','PHARMA'),
  ('SHREECEM','INFRA'),
  ('SHRIPISTON','AUTO'),
  ('SHRIRAMFIN','FINANCE'),
  ('SHYAMMETL','INFRA'),
  ('SIEMENS','INFRA'),
  ('SIGNATURE','REALTY'),
  ('SJVN','ENERGY'),
  ('SKFINDIA','AUTO'),
  ('SKIPPER','INFRA'),
  ('SKYGOLD','FMCG'),
  ('SMSPHARMA','PHARMA'),
  ('SOBHA','REALTY'),
  ('SOLARINDS','METAL'),
  ('SONACOMS','AUTO'),
  ('SONATSOFTW','IT'),
  ('SPARC','PHARMA'),
  ('SPLPETRO','METAL'),
  ('SPMLINFRA','INFRA'),
  ('SRF','METAL'),
  ('SSWL','AUTO'),
  ('STAR','PHARMA'),
  ('STARHEALTH','FINANCE'),
  ('STYRENIX','METAL'),
  ('SUDARSCHEM','METAL'),
  ('SUMICHEM','METAL'),
  ('SUNDARMFIN','FINANCE'),
  ('SUNDRMFAST','INFRA'),
  ('SUNPHARMA','PHARMA'),
  ('SUNTECK','REALTY'),
  ('SUNTV','FMCG'),
  ('SUPREMEIND','INFRA'),
  ('SUPRIYA','PHARMA'),
  ('SURYAROSNI','INFRA'),
  ('SUVEN','PHARMA'),
  ('SUZLON','INFRA'),
  ('SWANCORP','METAL'),
  ('SWIGGY','FMCG'),
  ('SWSOLAR','INFRA'),
  ('SYNGENE','PHARMA'),
  ('SYRMA','INFRA'),
  ('TANLA','IT'),
  ('TARC','REALTY'),
  ('TARIL','INFRA'),
  ('TATACAP','FINANCE'),
  ('TATACHEM','METAL'),
  ('TATACOMM','TELECOM'),
  ('TATACONSUM','FMCG'),
  ('TATAELXSI','IT'),
  ('TATAINVEST','FINANCE'),
  ('TATAPOWER','ENERGY'),
  ('TATASTEEL','METAL'),
  ('TATATECH','IT'),
  ('TBOTEK','FMCG'),
  ('TCS','IT'),
  ('TDPOWERSYS','INFRA'),
  ('TECHM','IT'),
  ('TECHNOE','INFRA'),
  ('TEGA','INFRA'),
  ('TEJASNET','TELECOM'),
  ('TENNIND','AUTO'),
  ('TEXRAIL','INFRA'),
  ('TFCILTD','FINANCE'),
  ('THELEELA','FMCG'),
  ('THERMAX','INFRA'),
  ('THOMASCOOK','FMCG'),
  ('THYROCARE','PHARMA'),
  ('TI','FMCG'),
  ('TIINDIA','AUTO'),
  ('TIMETECHNO','INFRA'),
  ('TIMKEN','INFRA'),
  ('TIPSMUSIC','FMCG'),
  ('TIRUMALCHM','METAL'),
  ('TITAGARH','INFRA'),
  ('TITAN','FMCG'),
  ('TMB','FINANCE'),
  ('TMCV','INFRA'),
  ('TMPV','AUTO'),
  ('TORNTPHARM','PHARMA'),
  ('TORNTPOWER','ENERGY'),
  ('TRANSRAILL','INFRA'),
  ('TRAVELFOOD','FMCG'),
  ('TRENT','FMCG'),
  ('TRIDENT','FMCG'),
  ('TRITURBINE','INFRA'),
  ('TRIVENI','FMCG'),
  ('TTML','IT'),
  ('TVSMOTOR','AUTO'),
  ('UBL','FMCG'),
  ('UCOBANK','FINANCE'),
  ('UJJIVANSFB','FINANCE'),
  ('ULTRACEMCO','INFRA'),
  ('UNIONBANK','BANKING'),
  ('UNITDSPR','FMCG'),
  ('UNIVCABLES','INFRA'),
  ('UNOMINDA','AUTO'),
  ('UPL','METAL'),
  ('URBANCO','FMCG'),
  ('USHAMART','INFRA'),
  ('UTIAMC','FINANCE'),
  ('V2RETAIL','FMCG'),
  ('VADILALIND','FMCG'),
  ('VAIBHAVGBL','FMCG'),
  ('VARROC','AUTO'),
  ('VBL','FMCG'),
  ('VEDL','METAL'),
  ('VGUARD','FMCG'),
  ('VIJAYA','PHARMA'),
  ('VIKRAMSOLR','INFRA'),
  ('VIMTALABS','PHARMA'),
  ('VINATIORGA','METAL'),
  ('VIPIND','FMCG'),
  ('VMART','FMCG'),
  ('VMM','FMCG'),
  ('VOLTAMP','INFRA'),
  ('VOLTAS','FMCG'),
  ('VSTTILLERS','AUTO'),
  ('VTL','FMCG'),
  ('WAAREEENER','INFRA'),
  ('WAAREERTL','INFRA'),
  ('WABAG','ENERGY'),
  ('WALCHANNAG','INFRA'),
  ('WELCORP','INFRA'),
  ('WELENT','INFRA'),
  ('WELSPUNLIV','FMCG'),
  ('WENDT','INFRA'),
  ('WHEELS','AUTO'),
  ('WHIRLPOOL','FMCG'),
  ('WIPRO','IT'),
  ('WOCKPHARMA','PHARMA'),
  ('YATHARTH','PHARMA'),
  ('YESBANK','FINANCE'),
  ('ZAGGLE','IT'),
  ('ZEEL','FMCG'),
  ('ZENSARTECH','IT'),
  ('ZENTEC','INFRA'),
  ('ZFCVINDIA','AUTO'),
  ('ZYDUSLIFE','PHARMA'),
  ('ZYDUSWELL','FMCG')
)
UPDATE public.signals s
   SET sector = m.sector,
       sector_as_of = 'backfill-2026-10-02'
  FROM m
 WHERE s.symbol = m.symbol
   AND s.sector IS NULL;

-- sector_bias is deliberately NOT backfilled. It was the sector's momentum
-- classification ON THAT DATE, which sector_heatmap only covers from 2026-05
-- and which cannot be reconstructed before that. Left NULL rather than imputed:
-- a momentum reading invented three years later is not a weaker version of the
-- real thing, it is a different number wearing its name.

COMMENT ON COLUMN public.signals.sector IS
  'Sector from universe.SYMBOL_SECTOR_MAP. Read sector_as_of before using it: "recorded" means 06_push wrote it on the night of publication, "backfill-YYYY-MM-DD" means today''s map was applied retrospectively and a symbol reclassified since is attributed to its current sector.';

COMMENT ON COLUMN public.signals.sector_as_of IS
  'recorded = written at publication. backfill-YYYY-MM-DD = imputed on that date from the then-current sector map. Exists so an imputed sector can never be mistaken for an observed one, which is the mistake that made sector=OTHER invisible for seventeen months.';

COMMENT ON COLUMN public.signals.sector_bias IS
  'The sector''s momentum classification on the publication date (long/short/avoid). NULL on every row published before 2026-10-02 and not backfilled: it is a point-in-time reading that cannot be reconstructed, unlike the sector itself.';

-- Outcome rows carry the same lie and the same fix shape. Null them rather than
-- re-deriving here: update_outcomes re-reads signals and will now carry the real
-- sector through on its next pass.
UPDATE public.signal_outcomes SET sector = NULL WHERE sector = 'OTHER';

COMMENT ON COLUMN public.signal_outcomes.sector IS
  'Copied from the signals row at resolution time. Was the constant "OTHER" on all 831 rows to 2026-10-02, because the resolvers read a column that did not exist with a default that hid it; those were set NULL and are repopulated as rows re-resolve.';

-- ─────────────────────────────────────────────────────────────────────
-- 2. publication_kind: A LABEL LEAK, made honest.
--
--    The column arrived as NOT NULL DEFAULT 'signal', so every row published
--    before it existed was backfilled to 'signal'. That makes the value
--    indistinguishable between "06_push published this as actionable" and
--    "this predates the column" -- and since the column was added the same
--    week the watchlist shipped, the value correlates with date rather than
--    with actionability. Anything learning from this table would be reading
--    a timestamp disguised as a categorical.
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.signals ALTER COLUMN publication_kind DROP NOT NULL;

UPDATE public.signals
   SET publication_kind = NULL
 WHERE signal_date < DATE '2026-10-01';

COMMENT ON COLUMN public.signals.publication_kind IS
  'signal = published as ATLAS-actionable. candidate = watchlist only, never entered. NULL = published before this column existed, so actionability was never recorded -- do NOT read NULL as either value. market_open tests `= ''signal''` positively, so a NULL row is watch-only rather than tradeable.';

-- ─────────────────────────────────────────────────────────────────────
-- 3. DERIVED FIELDS, marked rather than dropped.
--
--    Dropping them would break signals.html, which renders rr_1, rr_2 and
--    the sub-scores. What they need is to stop reading like independent
--    measurements: score equals the sum of the five sub-scores on all 845
--    rows that have them, mean gap 0.00, zero exceptions -- so testing the
--    six as separate features, which the last analysis did, was testing one
--    quantity six ways.
-- ─────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.signals.score IS
  'DERIVED. Exactly the sum of score_regime + score_smc + score_technical + score_volume + score_rr -- verified on all 845 rows carrying sub-scores, mean gap 0.00. The six are one quantity and its decomposition, not six features. The score GATE was retired as non-predictive; this is kept for display and ranking.';

COMMENT ON COLUMN public.signals.score_smc IS
  'DERIVED component of score. See the comment on score: the five components sum to it exactly, so they are not independent of it or of each other.';
COMMENT ON COLUMN public.signals.score_regime IS 'DERIVED component of score. See score.';
COMMENT ON COLUMN public.signals.score_technical IS 'DERIVED component of score. See score.';
COMMENT ON COLUMN public.signals.score_volume IS 'DERIVED component of score. See score.';
COMMENT ON COLUMN public.signals.score_rr IS 'DERIVED component of score. See score.';

COMMENT ON COLUMN public.signals.rr_1 IS
  'CONSTANT 2.0 on every row, and rr_2 is constant 3.0. These are the fixed measurement yardstick the accuracy record is scored against (zone_entry.MEASURE_R1/R2), not a per-signal risk-reward -- ATLAS trades with no target at all. They carry no per-row information.';
COMMENT ON COLUMN public.signals.rr_2 IS 'CONSTANT 3.0. See rr_1.';

COMMENT ON COLUMN public.signals.sl_pct IS
  'DEPRECATED. 06_push has never written it, so it is NULL on 736 of 1,012 rows; signals.html rendered a bare "%" for those and now computes the distance from sl and entry_ref instead. Nothing reads this column.';

COMMENT ON COLUMN public.signals.vix_close IS
  'NULL on 1,006 of 1,012 rows and read by nothing. 03b carries vix_close on the frame but it is empty for almost every bar; treat this column as unpopulated rather than as a VIX series.';

-- ─────────────────────────────────────────────────────────────────────
-- VERIFY. All true.
-- ─────────────────────────────────────────────────────────────────────

SELECT
  (SELECT count(*) = 3 FROM information_schema.columns
     WHERE table_name = 'signals'
       AND column_name IN ('sector','sector_bias','sector_as_of'))        AS cols_added,
  (SELECT count(*) = 0 FROM public.signals WHERE sector IS NULL)          AS sector_backfilled,
  (SELECT count(*) > 0 FROM public.signals
     WHERE sector_as_of = 'backfill-2026-10-02')                          AS backfill_flagged,
  (SELECT count(*) = 0 FROM public.signal_outcomes WHERE sector = 'OTHER') AS other_cleared,
  (SELECT is_nullable = 'YES' FROM information_schema.columns
     WHERE table_name = 'signals' AND column_name = 'publication_kind')   AS pubkind_nullable,
  (SELECT count(*) = 0 FROM public.signals
     WHERE signal_date < DATE '2026-10-01'
       AND publication_kind IS NOT NULL)                                  AS history_nulled,
  (SELECT count(*) > 0 FROM public.signals
     WHERE signal_date >= DATE '2026-10-01'
       AND publication_kind = 'signal')                                   AS recent_kept,
  (SELECT col_description('public.signals'::regclass::oid, ordinal_position)
            LIKE 'DERIVED%' FROM information_schema.columns
     WHERE table_name = 'signals' AND column_name = 'score')              AS score_marked;
