#!/usr/bin/env bash
#
# ATLAS market-hours service — deployment.
#
#   sudo bash deploy/install.sh              # dry run: shows everything, changes nothing
#   sudo bash deploy/install.sh --apply      # does it
#
# Three steps:
#   1. /etc/atlas.env from the crontab header, root-owned, 600
#   2. the 09:37 market_open cron line commented out (crontab backed up first)
#   3. the unit and its timer installed; neither started, timer NOT enabled
#
# Nothing is started and nothing will start on its own. The service is
# timer-activated, and the timer is left disabled until the first session has
# been watched -- which is what "start it Monday and watch it" needs. Enabling
# the timer is one command, printed at the end.
#
# Dry run is the default because two of these three steps touch production
# state that is awkward to reverse -- a crontab you have already overwritten and
# an /etc file you have already replaced. Read the dry run, then --apply.
#
# SECRET VALUES ARE NEVER PRINTED. Names and lengths only, because this output
# tends to end up pasted into a terminal that is logged.

set -euo pipefail

APPLY=0
[[ "${1:-}" == "--apply" ]] && APPLY=1

REPO="${ATLAS_REPO:-/home/ubuntu/thestocklogic}"
ENV_FILE=/etc/atlas.env
UNIT_SRC="$REPO/deploy/atlas-market-hours.service"
UNIT_DST=/etc/systemd/system/atlas-market-hours.service
TIMER_SRC="$REPO/deploy/atlas-market-hours.timer"
TIMER_DST=/etc/systemd/system/atlas-market-hours.timer
REP_SRC="$REPO/deploy/atlas-engine-report.service"
REP_DST=/etc/systemd/system/atlas-engine-report.service
REPT_SRC="$REPO/deploy/atlas-engine-report.timer"
REPT_DST=/etc/systemd/system/atlas-engine-report.timer
STAMP="$(date -u +%Y%m%d%H%M%S)"
BACKUP_DIR="/var/backups/atlas"
CRON_USER="${ATLAS_CRON_USER:-ubuntu}"

REQUIRED=(SUPABASE_SERVICE_KEY TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID)
OPTIONAL=(SUPABASE_URL ZERODHA_API_KEY ZERODHA_API_SECRET ZERODHA_USER_ID
          ZERODHA_PASSWORD ZERODHA_TOTP_SECRET)

say()  { printf '%s\n' "$*"; }
step() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
would() { if (( APPLY )); then printf '   %s\n' "$*"; else printf '   [dry run] %s\n' "$*"; fi; }

if (( EUID != 0 )); then
  say "must run as root (sudo bash deploy/install.sh)"; exit 1
fi
if [[ ! -d "$REPO" ]]; then
  say "repo not found at $REPO — set ATLAS_REPO"; exit 1
fi
if [[ ! -f "$UNIT_SRC" || ! -f "$TIMER_SRC" || ! -f "$REP_SRC" || ! -f "$REPT_SRC" ]]; then
  say "unit or timer file missing under $REPO/deploy"; exit 1
fi

(( APPLY )) || say "DRY RUN — nothing will be changed. Re-run with --apply."

# ══════════════════════════════════════════════════════════════════
step "1. /etc/atlas.env from the crontab header"
# ══════════════════════════════════════════════════════════════════
CRON_RAW="$(crontab -u "$CRON_USER" -l 2>/dev/null || true)"
if [[ -z "$CRON_RAW" ]]; then
  say "   no crontab for $CRON_USER — set ATLAS_CRON_USER"; exit 1
fi

TMP_ENV="$(mktemp)"
chmod 600 "$TMP_ENV"
trap 'rm -f "$TMP_ENV"' EXIT

{
  echo "# Generated by deploy/install.sh at ${STAMP}Z from the ${CRON_USER} crontab."
  echo "# Source of truth for the systemd service, which cannot read a crontab."
  echo "# LIVE TRADING: decided by GO_LIVE_DATE in atlas/config.py (shadow"
  echo "# through 2026-09-17, live from 2026-09-18). ATLAS_LIVE overrides it:"
  echo "#   ATLAS_LIVE=false  forces SHADOW whatever the date -- the brake."
  echo "#   ATLAS_LIVE=true   forces LIVE early, for a deliberate test."
  echo "# Unset means the date decides. Setting it here needs only a restart."
} >> "$TMP_ENV"

missing=()
for name in "${REQUIRED[@]}" "${OPTIONAL[@]}"; do
  # Header assignments only: NAME=value at the start of a line, before the
  # schedule lines. Take the LAST one if the header sets it more than once,
  # matching how cron itself resolves duplicates.
  val="$(printf '%s\n' "$CRON_RAW" \
         | sed -n "s/^[[:space:]]*${name}=\(.*\)$/\1/p" \
         | tail -n1)"
  val="${val%\"}"; val="${val#\"}"
  val="${val%\'}"; val="${val#\'}"
  if [[ -n "$val" ]]; then
    printf '%s=%s\n' "$name" "$val" >> "$TMP_ENV"
    printf '   found %-24s (%d chars)\n' "$name" "${#val}"
  else
    printf '   ABSENT %-24s\n' "$name"
    for r in "${REQUIRED[@]}"; do [[ "$r" == "$name" ]] && missing+=("$name"); done
  fi
done

if (( ${#missing[@]} )); then
  say ""
  say "   MISSING REQUIRED: ${missing[*]}"
  say "   The service refuses to start without these (market_open.preflight)."
  say "   Add them to $ENV_FILE by hand after this runs, or to the crontab"
  say "   header and re-run. Not inventing values."
fi

if (( APPLY )); then
  [[ -f "$ENV_FILE" ]] && { mkdir -p "$BACKUP_DIR"; cp -a "$ENV_FILE" "$BACKUP_DIR/atlas.env.$STAMP"; \
                            say "   backed up existing $ENV_FILE -> $BACKUP_DIR/atlas.env.$STAMP"; }
  install -o root -g root -m 600 "$TMP_ENV" "$ENV_FILE"
  say "   wrote $ENV_FILE (root:root, 600)"
else
  would "write $ENV_FILE with $(grep -c '^[A-Z]' "$TMP_ENV") variable(s), root:root, 600"
fi

# ══════════════════════════════════════════════════════════════════
step "2. remove the 09:37 market_open cron line"
# ══════════════════════════════════════════════════════════════════
mkdir -p "$BACKUP_DIR"
CRON_BACKUP="$BACKUP_DIR/crontab.$CRON_USER.$STAMP"
if (( APPLY )); then
  printf '%s\n' "$CRON_RAW" > "$CRON_BACKUP"
  chmod 600 "$CRON_BACKUP"
  say "   crontab backed up -> $CRON_BACKUP"
else
  would "back up crontab -> $CRON_BACKUP"
fi

TARGETS="$(printf '%s\n' "$CRON_RAW" | grep -n 'market_open' | grep -v '^[0-9]*:[[:space:]]*#' || true)"
if [[ -z "$TARGETS" ]]; then
  say "   no active market_open line found — nothing to remove"
else
  say "   will comment out:"
  printf '%s\n' "$TARGETS" | sed 's/^/     /'
  # Commented, not deleted: reversible, and it leaves the reason next to the
  # line for whoever reads this crontab in six months.
  #
  # awk rather than sed. `sed "/x/{/y/!s|..|..|}"` is GNU-only -- BSD sed
  # rejects the one-line block with "bad flag in substitute command". Under
  # `set -e` that aborts the script here, AFTER /etc/atlas.env has already been
  # written, leaving the deploy half-done. awk behaves the same on both, so
  # this step can be tested somewhere other than the machine it runs on.
  NEW_CRON="$(printf '%s\n' "$CRON_RAW" | awk -v m="# disabled ${STAMP}Z, replaced by atlas-market-hours.service: " '
      /market_open/ && $0 !~ /^[[:space:]]*#/ { print m $0; next }
      { print }
  ')"
  if (( APPLY )); then
    printf '%s\n' "$NEW_CRON" | crontab -u "$CRON_USER" -
    say "   crontab updated"
  else
    would "comment those line(s) out and install the crontab"
  fi
fi

# ══════════════════════════════════════════════════════════════════
step "3. install the unit and timer (NOT started, timer NOT enabled)"
# ══════════════════════════════════════════════════════════════════
# VALIDATE BEFORE INSTALLING.
#
# StartLimitIntervalSec sat in [Service], where systemd does not recognise it.
# It logged "Unknown key ... ignoring" and carried on, so the rate limit meant
# to catch a crash loop was itself silently missing -- the failure it exists to
# prevent. Nothing refused, nothing broke, and the unit looked installed.
#
# systemd-analyze verify parses a unit the way systemd will and names every
# unknown key. Only unknown-key and syntax problems are fatal here: verify also
# reports things like a missing User on a non-running system, and a check that
# cries wolf gets ignored.
if command -v systemd-analyze >/dev/null 2>&1; then
  VERIFY_OUT="$(systemd-analyze verify "$UNIT_SRC" "$TIMER_SRC" "$REP_SRC" "$REPT_SRC" 2>&1 || true)"
  FATAL="$(printf '%s\n' "$VERIFY_OUT" | grep -iE "unknown key|unknown lvalue|invalid|failed to parse" || true)"
  if [[ -n "$FATAL" ]]; then
    say "   unit validation FAILED:"
    printf '%s\n' "$FATAL" | sed 's/^/     /'
    say "   refusing to install. Fix the unit files and re-run."
    exit 1
  fi
  [[ -n "$VERIFY_OUT" ]] && { say "   systemd-analyze notes (non-fatal):";
                              printf '%s\n' "$VERIFY_OUT" | sed 's/^/     /'; }
  say "   systemd-analyze verify: no unknown keys"
else
  say "   systemd-analyze not present — skipping unit validation"
fi

if (( APPLY )); then
  [[ -f "$UNIT_DST" ]] && cp -a "$UNIT_DST" "$BACKUP_DIR/atlas-market-hours.service.$STAMP"
  install -o root -g root -m 644 "$UNIT_SRC" "$UNIT_DST"
  install -o root -g root -m 644 "$TIMER_SRC" "$TIMER_DST"
  install -o root -g root -m 644 "$REP_SRC" "$REP_DST"
  install -o root -g root -m 644 "$REPT_SRC" "$REPT_DST"
  systemctl daemon-reload

  # The service used to carry WantedBy=multi-user.target, so an earlier run of
  # this script enabled it and every reboot started a session at whatever hour
  # the box came up. It is timer-activated now; drop that symlink if it is
  # there. Harmless when it is not.
  if systemctl is-enabled atlas-market-hours.service &>/dev/null; then
    systemctl disable atlas-market-hours.service >/dev/null 2>&1 || true
    say "   removed the boot-time enable on the service (the timer owns starting it)"
  fi

  say "   installed $UNIT_DST"
  say "   installed $TIMER_DST"
  say "   installed $REP_DST"
  say "   installed $REPT_DST"
  say "   service : $(systemctl is-active atlas-market-hours.service 2>&1) / $(systemctl is-enabled atlas-market-hours.service 2>&1 || echo 'timer-activated')"
  say "   timer   : $(systemctl is-enabled atlas-market-hours.timer 2>&1 || echo disabled)  <- disabled is correct until the first session is watched"
  systemctl enable atlas-engine-report.timer >/dev/null 2>&1 || true
  say "   report  : $(systemctl is-enabled atlas-engine-report.timer 2>&1 || echo disabled) (safe to enable now -- it only reads and sends)"
else
  would "install $UNIT_DST, $TIMER_DST, $REP_DST, $REPT_DST, daemon-reload"
  would "enable atlas-engine-report.timer (read-only, never trades)"
  would "drop any boot-time enable on the service; leave the timer DISABLED"
fi

step "done"
if (( APPLY )); then
  cat <<EOF
   Nothing is running and nothing will start by itself.

   Monday, to start and watch:

     sudo systemctl start atlas-market-hours
     journalctl -u atlas-market-hours -f

   After that session looks right, hand it to the timer for every
   weekday after:

     sudo systemctl enable --now atlas-market-hours.timer
     systemctl list-timers atlas-market-hours.timer

   To stop it mid-session:

     /pause in Telegram        halts entries within one cycle, process stays up
     sudo systemctl stop atlas-market-hours    stops the process

   To roll back:

     sudo systemctl disable --now atlas-market-hours.timer
     sudo systemctl stop atlas-market-hours.service
     sudo crontab -u $CRON_USER $CRON_BACKUP
EOF
else
  say "   dry run only. Re-run with --apply."
fi
