#!/usr/bin/env python3
"""
Run Radar detection and emit the writes as SQL instead of PostgREST calls.

    python3 -m tools.radar_emit_sql                      # newest session
    python3 -m tools.radar_emit_sql --date 2026-10-07
    python3 -m tools.radar_emit_sql --no-filings

WHY THIS EXISTS. radar/store.py writes with the service role over PostgREST,
and SUPABASE_SERVICE_KEY lives on the box and in the crontab header -- not on a
development machine. This runs the SAME detection, heat, levels, outcome and
card code and emits the result as SQL, so a first population can go in over a
database connection without a service key ever touching this host.

IT IS NOT A SECOND IMPLEMENTATION. Every number comes from radar/detect.py,
radar/heat.py, radar/levels.py, radar/outcomes.py and radar/cards.py -- the
modules the nightly run uses. Only the transport differs. The nightly job still
goes through radar/store.py.

NO GENERATED IDS ANYWHERE. radar_events.id is a bigserial, so the levels and
card rows would need it to link. Instead they are inserted with a SELECT keyed
on (symbol, event_date), which is a UNIQUE constraint -- so the SQL is
self-contained, order-independent after the events insert, and safe to re-run.
"""

from __future__ import annotations

import sys
import json
import logging
import argparse
from pathlib import Path
from datetime import date

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from radar import bars, detect, heat, levels, cards, outcomes, documents  # noqa: E402
from radar.config import load as load_config                              # noqa: E402

log = logging.getLogger("RADAR-EMIT")


def q(v) -> str:
    """A SQL literal. Doubles single quotes; None -> NULL."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (date,)):
        return "'" + v.isoformat() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def qj(obj) -> str:
    """A jsonb literal."""
    return q(json.dumps(obj, default=str)) + "::jsonb"


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    ap = argparse.ArgumentParser()
    ap.add_argument("--date")
    ap.add_argument("--no-filings", action="store_true")
    ap.add_argument("--out", default="-")
    a = ap.parse_args()

    cfg = load_config(use_table=False)
    on = date.fromisoformat(a.date) if a.date else bars.available_sessions()[-1]
    avail = set(bars.available_sessions())
    if on not in avail:
        log.error(f"no bhavcopy for {on} — refusing to emit a session that "
                  f"cannot be scored")
        return 1

    symbols, sector_map = detect.universe(cfg)
    log.info(f"session {on}, universe {len(symbols)}")

    hits = detect.detect_events(on, cfg, symbols, sector_map)
    scan = detect.scan_extremes(on, cfg, symbols, sector_map)
    triggered = {h["symbol"] for h in hits}

    # Heat and the Hot 10. Fresh tables, so every hit is new -- no dedup pass
    # is needed and none is faked.
    rows = []
    for h in hits:
        r = dict(h)
        r["severity"] = heat.severity(h)
        r["status"] = "live"
        rows.append(r)
    ranked = heat.rank_hot(rows, on, cfg)
    for i, r in enumerate(ranked["live"], start=1):
        r["rank"] = i

    all_events = ranked["live"] + ranked["displaced"]
    measured = {(m["symbol"], m["event_date"]): m
                for m in outcomes.sweep(all_events, cfg, as_of=on)}

    sess = None
    if not a.no_filings:
        try:
            sess = documents._session()
        except Exception as e:
            log.warning(f"NSE session unavailable ({e}) — causes will be "
                        f"unsourced")

    out = ["-- Radar R1 first population. Generated by tools/radar_emit_sql.py",
           f"-- session {on}, {len(all_events)} event(s), "
           f"{len(ranked['live'])} live",
           "BEGIN;", ""]

    # ── radar_events ─────────────────────────────────────────────
    vals = []
    for r in all_events:
        m = measured.get((r["symbol"], r["event_date"]))
        oc = m["outcome"] if m else {}
        vals.append(
            f"  ({q(r['symbol'])}, {q(r.get('sector'))}, "
            f"{q(r['trigger_type'])}, {q(r['event_date'])}, {q(r['status'])}, "
            f"{q(round(float(r['heat']), 4))}, {q(round(float(r['severity']), 3))}, "
            f"{q(r.get('move_pct'))}, {q(r.get('vol_multiple'))}, "
            f"{q(r.get('direction'))}, {qj(oc)})")
    out.append("INSERT INTO public.radar_events\n"
               "  (symbol, sector, trigger_type, event_date, status, heat,\n"
               "   severity, move_pct, vol_multiple, direction, outcome)\nVALUES")
    out.append(",\n".join(vals))
    out.append("ON CONFLICT (symbol, event_date) DO UPDATE SET\n"
               "  status = EXCLUDED.status, heat = EXCLUDED.heat,\n"
               "  severity = EXCLUDED.severity, outcome = EXCLUDED.outcome;")
    out.append("")

    # ── radar_scanner_daily ──────────────────────────────────────
    scan_rows = []
    for side in ("high", "low"):
        for r in scan[side]:
            r["promoted"] = r["symbol"] in triggered
            r["filing_recent"] = False
            if sess is not None:
                try:
                    r["filing_recent"] = documents.had_recent_filing(
                        r["symbol"], on, cfg, session=sess)
                except Exception as e:
                    log.warning(f"{r['symbol']}: filing flag failed ({e})")
            scan_rows.append(r)
    if scan_rows:
        vals = [
            f"  ({q(r['trade_date'])}, {q(r['symbol'])}, {q(r['side'])}, "
            f"{q(r.get('sector'))}, {q(r.get('close'))}, "
            f"{q(r.get('extreme_price'))}, {q(r.get('pct_from_extreme'))}, "
            f"{q(r.get('vol_multiple'))}, {q(r.get('volume'))}, "
            f"{q(r.get('delivery_pct'))}, {q(r['filing_recent'])}, "
            f"{q(r['promoted'])}, {q(r.get('rank_in_side'))})"
            for r in scan_rows]
        out.append("INSERT INTO public.radar_scanner_daily\n"
                   "  (trade_date, symbol, side, sector, close, extreme_price,\n"
                   "   pct_from_extreme, vol_multiple, volume, delivery_pct,\n"
                   "   filing_recent, promoted, rank_in_side)\nVALUES")
        out.append(",\n".join(vals))
        out.append("ON CONFLICT (trade_date, symbol, side) DO UPDATE SET\n"
                   "  vol_multiple = EXCLUDED.vol_multiple,\n"
                   "  filing_recent = EXCLUDED.filing_recent,\n"
                   "  promoted = EXCLUDED.promoted,\n"
                   "  rank_in_side = EXCLUDED.rank_in_side;")
        out.append("")

    # ── levels, documents and cards, for the live set ────────────
    doc_vals, hot = [], []
    for r in ranked["live"]:
        ed = r["event_date"]
        df = bars.frame_through(r["symbol"], ed)
        if df is None:
            log.warning(f"{r['symbol']}: no frame, skipped")
            continue
        vwap = bars.session_vwap(r["symbol"], ed)
        level_rows = levels.compute_all(df, cfg, vwap)

        # LEVELS, keyed on (symbol, event_date) rather than on an id.
        lv_vals = [
            f"  ((SELECT id FROM public.radar_events WHERE symbol="
            f"{q(r['symbol'])} AND event_date={q(ed)}), "
            f"{q(l['level_type'])}, {q(l['price'])}, {q(l.get('dist_pct'))}, "
            f"{q(l.get('ref_date'))})"
            for l in level_rows]
        if lv_vals:
            out.append("INSERT INTO public.radar_levels\n"
                       "  (event_id, level_type, price, dist_pct, ref_date)\nVALUES")
            out.append(",\n".join(lv_vals))
            out.append("ON CONFLICT (event_id, level_type) DO UPDATE SET\n"
                       "  price = EXCLUDED.price, dist_pct = EXCLUDED.dist_pct;")
            out.append("")

        if sess is not None:
            cause = documents.attribute(r["symbol"], ed, cfg, session=sess)
            for d in cause.get("documents") or []:
                doc_vals.append(
                    f"  ({q(d['source'])}, {q(d.get('url'))}, "
                    f"{q(d.get('published_at'))}, "
                    f"ARRAY[{q((d.get('symbols') or [r['symbol']])[0])}]::text[], "
                    f"{q(d.get('title'))}, {q(d.get('body'))}, "
                    f"{q(d.get('category'))}, {q(d['text_hash'])})")
        else:
            cause = {"cause_text": documents.NO_CAUSE_TEXT, "cause_url": None,
                     "cause_published_at": None, "cause_sourced": False,
                     "checked": False, "documents": []}

        srow = bars.session_row(r["symbol"], ed)
        ev = dict(r)
        if srow is not None:
            import pandas as pd
            dp = srow.get("delivery_pct")
            ev["delivery_pct"] = (None if dp is None or pd.isna(dp)
                                  else round(float(dp), 2))
            ev["close"] = round(float(srow["close"]), 2)
        oc = measured.get((r["symbol"], ed))
        payload = cards.build(ev, level_rows, cause,
                              oc["outcome"] if oc else None,
                              r["sessions_since"], on, cfg)
        status, notes = cards.validate(payload)

        out.append("INSERT INTO public.radar_card_versions\n"
                   "  (event_id, trade_date, payload, validation_status,\n"
                   "   validation_notes)\nSELECT e.id, "
                   f"{q(on)}, {qj(payload)}, {q(status)}, {q(notes)}\n"
                   f"  FROM public.radar_events e\n"
                   f" WHERE e.symbol={q(r['symbol'])} AND e.event_date={q(ed)}\n"
                   "ON CONFLICT (event_id, trade_date) DO UPDATE SET\n"
                   "  payload = EXCLUDED.payload,\n"
                   "  validation_status = EXCLUDED.validation_status;")
        out.append("")

        hot.append({"rank": r["rank"], "symbol": r["symbol"],
                    "move_pct": r.get("move_pct"),
                    "vol_multiple": r.get("vol_multiple"),
                    "severity": r["severity"], "heat": r["heat"],
                    "sessions_since": r["sessions_since"],
                    "trigger": r["trigger_type"],
                    "sector": r.get("sector"),
                    "cause": cause["cause_text"],
                    "sourced": bool(cause.get("cause_sourced")),
                    "cause_url": cause.get("cause_url"),
                    "validation": status})

    if doc_vals:
        # Deduped on text_hash by the constraint; the same filing can be
        # returned for two symbols in one sweep.
        seen, uniq = set(), []
        for v in doc_vals:
            if v not in seen:
                seen.add(v)
                uniq.append(v)
        out.insert(4, "")
        out.insert(4, "ON CONFLICT (text_hash) DO NOTHING;")
        out.insert(4, ",\n".join(uniq))
        out.insert(4, "INSERT INTO public.radar_documents\n"
                      "  (source, url, published_at, symbols, title, body,\n"
                      "   category, text_hash)\nVALUES")

    out.append("COMMIT;")
    sql = "\n".join(out)

    if a.out == "-":
        print(sql)
    else:
        Path(a.out).write_text(sql)
        log.info(f"wrote {a.out} ({len(sql)} bytes)")

    # The Hot 10, to stderr so it does not pollute the SQL on stdout.
    print(f"\n{'=' * 104}\nHOT {len(hot)} — session {on}\n{'=' * 104}",
          file=sys.stderr)
    print(f"{'#':>2}  {'SYMBOL':<12}{'MOVE%':>8}{'VOLx':>8}{'SEV':>8}{'HEAT':>8}"
          f"{'SESS':>5}  {'TRIGGER':<9} CAUSE", file=sys.stderr)
    print('-' * 104, file=sys.stderr)
    for h in hot:
        cause = h["cause"]
        if not h["sourced"]:
            cause = "no disclosed trigger"
        print(f"{h['rank']:>2}  {h['symbol']:<12}{h['move_pct']:>8.2f}"
              f"{(h['vol_multiple'] or 0):>8.2f}{h['severity']:>8.2f}"
              f"{h['heat']:>8.3f}{h['sessions_since']:>5}  "
              f"{h['trigger']:<9} {cause[:44]}", file=sys.stderr)
    n_src = sum(1 for h in hot if h["sourced"])
    print('-' * 104, file=sys.stderr)
    print(f"{n_src} of {len(hot)} with a cited exchange filing; "
          f"{len(hot) - n_src} unsourced. "
          f"{sum(1 for h in hot if h['validation'] != 'passed')} card(s) failed "
          f"validation.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
